from __future__ import annotations

import json
import os
from pathlib import Path

import httpx

from server.core import generate_insights, local_funasr_transcript, project_to_markdown

ROOT = Path(__file__).resolve().parent
WORKSPACE = ROOT.parent
AUDIO_PATH = Path("/Users/neoco/Documents/asr原始文件/04-24 内部会议. 芯片与工具链进展.mp3")
OUTPUT_DIR = WORKSPACE / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

os.environ.setdefault("HOME", str(WORKSPACE / ".cache" / "home"))
os.environ.setdefault("MODELSCOPE_CACHE", str(WORKSPACE / ".cache" / "modelscope"))
os.environ.setdefault("MODELSCOPE_CREDENTIALS_PATH", str(WORKSPACE / ".cache" / "modelscope" / "credentials"))
os.environ.setdefault("FUNASR_MODEL", "SenseVoiceSmall")
os.environ.setdefault("FUNASR_CHUNK_SECONDS", "600")
os.environ.setdefault("FUNASR_BATCH_SIZE_S", "300")

PROJECT_TITLE = "04-24 内部会议. 芯片与工具链进展"
BASE_URL = os.environ.get("RECORDER_AI_BASE_URL", "http://127.0.0.1:8878")


def write_json(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> None:
    if not AUDIO_PATH.exists():
        raise FileNotFoundError(AUDIO_PATH)

    segments = local_funasr_transcript(AUDIO_PATH)
    if not segments:
        raise RuntimeError("Local FunASR produced no transcript segments; refusing to create a fake result.")

    project = {
        "id": "real-asr-local-funasr",
        "title": PROJECT_TITLE,
        "scene": "meeting",
        "glossary": ["芯片", "工具链", "编译器", "内部会议", "AI", "研发", "适配", "版本"],
        "audio": {
            "name": AUDIO_PATH.name,
            "path": str(AUDIO_PATH),
            "size": AUDIO_PATH.stat().st_size,
            "type": "audio/mpeg",
        },
        "duration": 0,
        "segments": segments,
        "tags": ["#芯片", "#工具链", "#内部会议"],
        "todos": [],
        "insights": None,
    }
    generate_insights(project)

    raw_json_path = OUTPUT_DIR / "04-24 内部会议. 芯片与工具链进展-真实FunASR结果.json"
    md_path = OUTPUT_DIR / "04-24 内部会议. 芯片与工具链进展-真实FunASR校对稿.md"
    report_path = OUTPUT_DIR / "04-24 内部会议. 芯片与工具链进展-端到端测试报告.json"

    write_json(raw_json_path, {"source": "local_funasr", "segment_count": len(segments), "project": project})
    md_path.write_text(project_to_markdown(project), encoding="utf-8")

    api_result = {"checked": False}
    try:
        with httpx.Client(base_url=BASE_URL, timeout=120, trust_env=False) as client:
            health = client.get("/api/health")
            health.raise_for_status()
            created = client.post("/api/projects", json={
                "title": PROJECT_TITLE,
                "scene": "meeting",
                "glossary": project["glossary"],
            })
            created.raise_for_status()
            project_id = created.json()["project"]["id"]
            with AUDIO_PATH.open("rb") as f:
                uploaded = client.post(f"/api/projects/{project_id}/upload", files={"file": (AUDIO_PATH.name, f, "audio/mpeg")})
            uploaded.raise_for_status()
            updated = client.put(f"/api/projects/{project_id}", json={"segments": segments, "insights": project["insights"], "tags": project["tags"]})
            updated.raise_for_status()
            exported = client.get(f"/api/projects/{project_id}/export.md")
            exported.raise_for_status()
            api_md_path = OUTPUT_DIR / "04-24 内部会议. 芯片与工具链进展-后端导出校对稿.md"
            api_md_path.write_text(exported.text, encoding="utf-8")
            api_result = {
                "checked": True,
                "project_id": project_id,
                "health": health.json(),
                "upload_size": uploaded.json()["project"]["audio"]["size"],
                "export_path": str(api_md_path),
            }
    except Exception as exc:
        api_result = {"checked": False, "error": f"{type(exc).__name__}: {exc}"}

    report = {
        "status": "passed" if api_result.get("checked") else "asr_completed_api_check_failed",
        "source": "local_funasr",
        "audio_path": str(AUDIO_PATH),
        "audio_size": AUDIO_PATH.stat().st_size,
        "segments": len(segments),
        "outputs": {
            "json": str(raw_json_path),
            "markdown": str(md_path),
        },
        "api": api_result,
        "note": "No fallback transcript was used. Result is generated by local FunASR only.",
    }
    write_json(report_path, report)
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
